### ISSUE TITLE
code location

### ISSUE THREAD

**Issue by TAY-985** [jayleicn/TVRetrieval#11]
Hi , i want to know where is the ConSe code and the Single Video Moment Retrieval.  loss function ,but i could not find it.
<img width="481" alt="1637738252(1)" src="https://user-images.githubusercontent.com/65696081/143192407-8643b0da-9d37-4de1-9ab6-f46cf6a5546d.png">
<img width="395" alt="1637738274(1)" src="https://user-images.githubusercontent.com/65696081/143192452-d7c70df8-5aa1-41b9-aaca-ef32c6a58b6d.png">

**Comment by jayleicn** [comment]
Hi @TAY-985, here is what you are looking for: https://github.com/jayleicn/TVRetrieval/blob/master/baselines/crossmodal_moment_localization/model_xml.py#L160-L165
