### ISSUE TITLE
Segmentation fault while running Language Model Fine-tuning

### ISSUE THREAD

**Issue by Worm4047** [jayleicn/TVRetrieval#4]
Hi,
I've been trying to finetune the language model but I'm getting segmentation fault while doing so.
I get the same issue when I try to run the lm_finetuning_on_single_sentences.py directly, this happens when I comment out invocation of main() like this

```
if __name__ == "__main__":
    # main()
```

**Comment by jayleicn** [comment]
Hi @Worm4047, Not sure what went wrong here, I guess you may find some answer in the huggingface/transformers repo?
