### ISSUE TITLE
About data collection

### ISSUE THREAD

**Issue by onlyonewater** [jayleicn/TVRetrieval#6]
Hi, in the data collection part, What automatic tool do you use to check the quality of the annotations in the automatic check part？

**Comment by jayleicn** [comment]
Hi @onlyonewater,

It is not a specific tool, but a set of functions and tools that checks:
- Whether the provided description has reached the desired length.
- Whether all the other required blanks are filled.
- Whether it is a direct copy of the subtitle sentences -- for this we used a simple retrieval model that tries to retrieve a subtitle given the description. If the GT subtitle ranks among the top 5 or 10 in the retrieval results, the system would prompt the workers to rewrite or paraphrase their descriptions.

Best,
Jie

**Comment by onlyonewater** [comment]
Oh, can these functions of the tool call API directly or need to be designed by ourselves??

**Comment by jayleicn** [comment]
You have to design these manually with javascript, and for the last one, you need a python backend as well.

**Comment by onlyonewater** [comment]
OK, I get it. Thanks!!!
